# Домашнее задание 1

## 1. Какие ещё существуют коды типов?

#### Помимо i (I) - знаковый (беззнаковый) int, в библиотеке array существуют ещё такие коды типов, как: b (B) - знаковый (беззнаковый) char, h (H) - знаковый (беззнаковый) short, l (L) - знаковый (беззнаковый) long, q (Q) - знаковый (беззнаковый) long long, f - float, d - double, u - Unicode char.

## 2. Напишите код, подобный приведенному выше, но с другим типом

In [8]:
import array
import sys

a1 = array.array('u', ['a', 'b', 'c'])
print(sys.getsizeof(a1))
print(type(a1))

86
<class 'array.array'>


## 3. Напишите код для создания массива с 5 значениями, располагающимися через равные интервалы в диапазоне от 0 до 1

In [45]:
import numpy as np

a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


## 4. Напишите код для создания массива с 5 равномерно распределенными случайными значениями в диапазоне от 0 до 1

In [24]:
a = np.random.uniform(0, 1, 5)
print(a)

[0.67046751 0.4173048  0.55868983 0.14038694 0.19810149]


## 5. Напишите код для создания массива с 5 нормально распределенными случайными значениями с мат. ожиданием = 0 и дисперсией 1

In [50]:
a = np.random.normal(0, 1, 5)
print(a)

[0.53825057 1.52826025 1.95667685 0.47820035 0.11934521]


## 6. Напишите код для создания массива с 5 случайнвми целыми числами в от [0, 10)

In [46]:
a = np.random.randint(10, size=5)
print(a)

[5 1 9 3 4]


## 7. Написать код для создания срезов массива 3 на 4
## - первые две строки и три столбца
## - первые три строки и второй столбец
## - все строки и столбцы в обратном порядке
## - второй столбец
## - третья строка

In [101]:
a = np.random.randint(10, size=(3, 4))
print(a)

[[2 7 2 6]
 [0 9 2 6]
 [6 2 7 7]]


In [102]:
print(a[:2, :3])

[[2 7 2]
 [0 9 2]]


In [103]:
print(a[:3, 1])

[7 9 2]


In [104]:
print(a[::-1, ::-1])

[[7 7 2 6]
 [6 2 9 0]
 [6 2 7 2]]


In [105]:
print(a[:, 1])

[7 9 2]


In [106]:
print(a[2, :])

[6 2 7 7]


## 8. Продемонстрируйте, как сделать срез-копию

In [107]:
b = a[:2, :3].copy()
b[0, 0] = 100
print(b)
print(a[:2, :3])

[[100   7   2]
 [  0   9   2]]
[[2 7 2]
 [0 9 2]]


## 9. Продемонстрируйте использование newaxis для получения вектора-столбца и вектора-строки


In [108]:
a = np.array([1, 2, 3])
print(a[np.newaxis, :])
print(a[:, np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]


## 10. Разберитесь, как работает метод dstack

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dstack([a, b]))

[[[1 4]
  [2 5]
  [3 6]]]


## 11. Разберитесь, как работают методы split, vsplit, hsplit, dsplit

In [92]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.split(a, 3))
print(np.vsplit(a, 3))
print(np.hsplit(a, 3))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [93]:
a = np.dstack([a, a, a])
print(np.dsplit(a, 3))

[array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]]), array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]]), array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])]


## 12. Привести пример использования всех универсальных функций, которые я привел

In [134]:
a = np.random.randint(10, size=(3, 3))
print(a)

[[6 8 8]
 [9 2 7]
 [5 5 4]]


In [135]:
print(a - 1)

[[5 7 7]
 [8 1 6]
 [4 4 3]]


In [136]:
print(-a)

[[-6 -8 -8]
 [-9 -2 -7]
 [-5 -5 -4]]


In [137]:
print(a / 2)

[[3.  4.  4. ]
 [4.5 1.  3.5]
 [2.5 2.5 2. ]]


In [138]:
print(a // 2)

[[3 4 4]
 [4 1 3]
 [2 2 2]]


In [139]:
print(a ** 2)

[[36 64 64]
 [81  4 49]
 [25 25 16]]


In [140]:
print(a % 2)

[[0 0 0]
 [1 0 1]
 [1 1 0]]


In [141]:
print(np.abs(a))

[[6 8 8]
 [9 2 7]
 [5 5 4]]


In [142]:
print(np.sin(a))

[[-0.2794155   0.98935825  0.98935825]
 [ 0.41211849  0.90929743  0.6569866 ]
 [-0.95892427 -0.95892427 -0.7568025 ]]


In [143]:
print(np.cos(a))

[[ 0.96017029 -0.14550003 -0.14550003]
 [-0.91113026 -0.41614684  0.75390225]
 [ 0.28366219  0.28366219 -0.65364362]]


In [144]:
print(np.tan(a))

[[-0.29100619 -6.79971146 -6.79971146]
 [-0.45231566 -2.18503986  0.87144798]
 [-3.38051501 -3.38051501  1.15782128]]


In [145]:
print(np.exp(a))

[[4.03428793e+02 2.98095799e+03 2.98095799e+03]
 [8.10308393e+03 7.38905610e+00 1.09663316e+03]
 [1.48413159e+02 1.48413159e+02 5.45981500e+01]]


In [146]:
print(np.log(a))

[[1.79175947 2.07944154 2.07944154]
 [2.19722458 0.69314718 1.94591015]
 [1.60943791 1.60943791 1.38629436]]
