# 1. Что надо изменить в последнем примере, чтобы он заработал без ошибок (транслирование)?

In [6]:
import numpy as np

a = np.ones((3, 3))
b = np.arange(3)

# (3, 3)  (3, 3)    (3, 3)
# (3,) -> (1, 3) -> (3, 3)

print(a + b)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


## Или:

In [7]:
a = np.ones((3, 2))
b = np.arange(2)

# (3, 2)  (3, 2)    (3, 2)
# (2,) -> (1, 2) -> (3, 2)

print(a + b)

[[1. 2.]
 [1. 2.]
 [1. 2.]]


# 2. Пример для y. Вычислить количество элементов (по обоим размерностям), значения которых больше 3 и меньше 9

In [13]:
y = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.sum((y > 3) & (y < 9), axis=0))
print(np.sum((y > 3) & (y < 9), axis=1))
print(np.sum((y > 3) & (y < 9)))

[1 1 1 1 1]
[2 3]
5
