# 1. Привести различные способы создания объектов типа Series <br>
# Для создания Series можно использовать <br>
# - списки Python или массивы NumPy <br>
# - скалярные значение <br>
# - словари

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.Series([1, 2, 3, 4, 5])
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
data = pd.Series(
    {
        'a': 1,
        'b': 2,
        'c': 3,
        'd': 4,
        'e': 5
    }
)
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [4]:
data = pd.Series(10, index=[0, 1, 2, 3, 4])
data

0    10
1    10
2    10
3    10
4    10
dtype: int64

# 2. Привести различные способы создания объектов типа DataFrame <br>
# DataFrame. Способы создания <br>
# - через объекты Series <br>
# - списки словарей <br>
# - словари объектов Series <br>
# - двумерный массив NumPy <br>
# - структурированный массив Numpy <br>

In [10]:
data1 = pd.Series([1, 2, 3, 4, 5])
data2 = pd.Series([6, 7, 8, 9, 10])

df = pd.DataFrame([data1, data2])
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [11]:
data = [
    {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5},
    {'a': 6, 'b': 7, 'c': 8, 'd': 9, 'e': 10}
]

df = pd.DataFrame(data)
df

a  b  c  d   e
0  1  2  3  4   5
1  6  7  8  9  10

In [12]:
df = pd.DataFrame({"data1": data1, "data2": data2})
df

data1  data2
0      1      6
1      2      7
2      3      8
3      4      9
4      5     10

In [13]:
arr = np.random.random((5, 5))
df = pd.DataFrame(arr)

df

0         1         2         3         4
0  0.234190  0.405404  0.370506  0.655198  0.667873
1  0.135482  0.787646  0.808201  0.981781  0.881831
2  0.855506  0.863191  0.609837  0.519648  0.518078
3  0.764291  0.172374  0.310349  0.876889  0.684483
4  0.008802  0.083173  0.342496  0.295688  0.652859

In [16]:
data = np.array([(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')], dtype=[('number', 'int32'), ('letter', 'U10')])
df = pd.DataFrame(data)

df

number letter
0       1      a
1       2      b
2       3      c
3       4      d
4       5      e

# 3. Объедините два объекта Series с неодинаковыми множествами ключей (индексов) так, чтобы вместо NaN было установлено значение 1

In [17]:
population_dict = {
    "city_1": 1001,
    "city_2": 1002,
    "city_3": 1003,
    "city_41": 1004,
    "city_51": 1005,
}

area_dict = {
    "city_1": 9991,
    "city_2": 9992,
    "city_3": 9993,
    "city_42": 9994,
    "city_52": 9995,
}

population = pd.Series(population_dict)
area = pd.Series(area_dict)

In [23]:
states = pd.DataFrame({
    "population": population,
    "area": area,
})

states.fillna(1)

population    area
city_1       1001.0  9991.0
city_2       1002.0  9992.0
city_3       1003.0  9993.0
city_41      1004.0     1.0
city_42         1.0  9994.0
city_51      1005.0     1.0
city_52         1.0  9995.0

# 4. Переписать пример с транслирование для DataFrame так, чтобы вычитание происходило по СТОЛБЦАМ

In [24]:
rng = np.random.default_rng(1)
A = rng.integers(0, 10, (3, 4))
print(A)

[[4 5 7 9]
 [0 1 8 9]
 [2 3 8 4]]


In [27]:
df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
df

a  b  c  d
0  4  5  7  9
1  0  1  8  9
2  2  3  8  4

In [31]:
print(df.iloc[:, 0])
print(df.sub(df.iloc[:, 0], axis=0))

0    4
1    0
2    2
Name: a, dtype: int64
   a  b  c  d
0  0  1  3  5
1  0  1  8  9
2  0  1  6  2


# 5. На примере объектов DataFrame продемонстрируйте использование методов ffill() и bfill()

In [32]:
data = {'a': [1, np.nan, np.nan, 4], 'b': [np.nan, 2, 3, np.nan]}
df = pd.DataFrame(data)
df

a    b
0  1.0  NaN
1  NaN  2.0
2  NaN  3.0
3  4.0  NaN

In [33]:
df.ffill()

a    b
0  1.0  NaN
1  1.0  2.0
2  1.0  3.0
3  4.0  3.0

In [34]:
df.bfill()

a    b
0  1.0  2.0
1  4.0  2.0
2  4.0  3.0
3  4.0  NaN