# Лекция 4

In [9]:
import numpy as np
import pandas as pd

## Если размерность данных > 2, то используют иерархическую индексацию (мультииндекс). В один индекс включается несколько уровней.

In [4]:
index = [
    ('city_1', 2010),
    ('city_1', 2020),
    ('city_2', 2010),
    ('city_2', 2020),
    ('city_3', 2010),
    ('city_3', 2020),
]

population = [
    101,
    201,
    102,
    202,
    103,
    203
]

pop = pd.Series(population, index = index)
print(pop)
print(pop[[i for i in pop.index if i[1] == 2020]])

(city_1, 2010)    101
(city_1, 2020)    201
(city_2, 2010)    102
(city_2, 2020)    202
(city_3, 2010)    103
(city_3, 2020)    203
dtype: int64
(city_1, 2020)    201
(city_2, 2020)    202
(city_3, 2020)    203
dtype: int64


### MultiIndex

In [6]:
index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)

print(pop)
print(pop[:, 2020])

city_1  2010    101
        2020    201
city_2  2010    102
        2020    202
city_3  2010    103
        2020    203
dtype: int64
city_1    201
city_2    202
city_3    203
dtype: int64


In [7]:
pop_df = pop.unstack()
print(pop_df)

        2010  2020
city_1   101   201
city_2   102   202
city_3   103   203


In [8]:
print(pop_df.stack())

city_1  2010    101
        2020    201
city_2  2010    102
        2020    202
city_3  2010    103
        2020    203
dtype: int64


In [13]:
index = [
    ('city_1', 2010, 1),
    ('city_1', 2010, 2),

    ('city_1', 2020, 1),
    ('city_1', 2020, 2),

    ('city_2', 2010, 1),
    ('city_2', 2010, 2),

    ('city_2', 2020, 1),
    ('city_2', 2020, 2),

    ('city_3', 2010, 1),
    ('city_3', 2010, 2),

    ('city_3', 2020, 1),
    ('city_3', 2020, 2)
]

population = [
    101,
    1010,
    201,
    2010,
    102,
    1020,
    202,
    2020,
    103,
    1030,
    203,
    2030
]

pop = pd.Series(population, index = index)
print(pop)

(city_1, 2010, 1)     101
(city_1, 2010, 2)    1010
(city_1, 2020, 1)     201
(city_1, 2020, 2)    2010
(city_2, 2010, 1)     102
(city_2, 2010, 2)    1020
(city_2, 2020, 1)     202
(city_2, 2020, 2)    2020
(city_3, 2010, 1)     103
(city_3, 2010, 2)    1030
(city_3, 2020, 1)     203
(city_3, 2020, 2)    2030
dtype: int64


In [17]:
index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)
print(pop[:, 2010])
print(pop[:, :, 2])

city_1  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_2  2010  1     102
              2    1020
        2020  1     202
              2    2020
city_3  2010  1     103
              2    1030
        2020  1     203
              2    2030
dtype: int64
city_1  1     101
        2    1010
city_2  1     102
        2    1020
city_3  1     103
        2    1030
dtype: int64
city_1  2010    1010
        2020    2010
city_2  2010    1020
        2020    2020
city_3  2010    1030
        2020    2030
dtype: int64


In [19]:
pop_df = pop.unstack()
print(pop_df)

               1     2
city_1 2010  101  1010
       2020  201  2010
city_2 2010  102  1020
       2020  202  2020
city_3 2010  103  1030
       2020  203  2030


In [20]:
print(pop_df.stack())

city_1  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_2  2010  1     102
              2    1020
        2020  1     202
              2    2020
city_3  2010  1     103
              2    1030
        2020  1     203
              2    2030
dtype: int64


In [26]:
pop_df = pd.DataFrame(
    {
        "total": pop,
        "something": [
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21
        ]   
    }
)

print(pop_df)
print(pop_df["something"])

               total  something
city_1 2010 1    101         10
            2   1010         11
       2020 1    201         12
            2   2010         13
city_2 2010 1    102         14
            2   1020         15
       2020 1    202         16
            2   2020         17
city_3 2010 1    103         18
            2   1030         19
       2020 1    203         20
            2   2030         21
city_1  2010  1    10
              2    11
        2020  1    12
              2    13
city_2  2010  1    14
              2    15
        2020  1    16
              2    17
city_3  2010  1    18
              2    19
        2020  1    20
              2    21
Name: something, dtype: int64


In [28]:
pop_df_1 = pop_df.loc["city_1", "something"]
print(pop_df_1)

2010  1    10
      2    11
2020  1    12
      2    13
Name: something, dtype: int64


### Как можно создавать мультииндексы:
### - список массивов, задающих значение индекса на каждом уровне
### - список кортежей, задающих значение индекса в каждой точке
### - декартово произведение обычных индексов
### - описание внутреннего представления: levels, codes

In [29]:
i1 = pd.MultiIndex.from_arrays(
    [
        ['a', 'a', 'b', 'b'],
        [1, 2, 1, 2]
    ]
)
print(i1)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [31]:
i2 = pd.MultiIndex.from_tuples(
    [
        ('a', 1),
        ('a', 2),
        ('b', 1),
        ('b', 2),
    ]
)
print(i2)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [33]:
i3 = pd.MultiIndex.from_product(
    [
        ['a', 'b'],
        [1, 2]
    ]
)
print(i3)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [35]:
i4 = pd.MultiIndex(
    levels = [
        ['a', 'b', 'c'],
        [1, 2]
    ],
    codes = [
        [0, 0, 1, 1, 2, 2], # a a b b c c
        [0, 1, 0, 1, 0, 1]  # 1 2 1 2 1 2
    ]
)
print(i4)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )


### Уровням можно задавать названия.

In [36]:
data = {
    ('city_1', 2010): 100,
    ('city_1', 2020): 200,
    ('city_2', 2010): 1001,
    ('city_2', 2020): 2001,
}

s = pd.Series(data)
print(s)

city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64


In [38]:
s.index.names = ["city", "year"]
print(s)

city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64


In [40]:
index = pd.MultiIndex.from_product(
    [
        ["city_1", "city_2"],
        ["2010", "2020"]
    ],
    names=["city", "year"]
)

columns = pd.MultiIndex.from_product(
    [
        ["person_1", "person_2", "person_3"],
        ["job_1", "job_2"]
    ],
    names=["worker", "job"]
)

rng = np.random.default_rng(1)
data = rng.random((4, 6))

data_df = pd.DataFrame(data, index=index, columns=columns)
print(data_df)

worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city   year                                                            
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737


### Индексация и срезы (по мультииндексу)

In [46]:
data = {
    ('city_1', 2010): 100,
    ('city_1', 2020): 200,
    ('city_2', 2010): 1001,
    ('city_2', 2020): 2001,
    ('city_3', 2010): 10001,
    ('city_3', 2020): 20001,
}

s = pd.Series(data)
s.index.names = ["city", "year"]

print(s["city_1", 2010])
print(s["city_1"])
print(s.loc["city_1":"city_2"])
print(s[s > 2000])
print(s[["city_1", "city_3"]])

100
year
2010    100
2020    200
dtype: int64
city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64
city    year
city_2  2020     2001
city_3  2010    10001
        2020    20001
dtype: int64
city    year
city_1  2010      100
        2020      200
city_3  2010    10001
        2020    20001
dtype: int64


### Перегруппировка мультииндексов

In [50]:
index = pd.MultiIndex.from_product(
    [
        ['a', 'c', 'b'],
        [1, 2]
    ]
)

rng = np.random.default_rng(1)
data = pd.Series(rng.random(6), index = index)
print(data)
# print(data['a':'b'])
data = data.sort_index()
print(data['a':'b'])

a  1    0.511822
   2    0.950464
c  1    0.144160
   2    0.948649
b  1    0.311831
   2    0.423326
dtype: float64
a  1    0.511822
   2    0.950464
b  1    0.311831
   2    0.423326
dtype: float64


In [54]:
index = [
    ('city_1', 2010, 1),
    ('city_1', 2010, 2),

    ('city_1', 2020, 1),
    ('city_1', 2020, 2),

    ('city_2', 2010, 1),
    ('city_2', 2010, 2),

    ('city_2', 2020, 1),
    ('city_2', 2020, 2),

    ('city_3', 2010, 1),
    ('city_3', 2010, 2),

    ('city_3', 2020, 1),
    ('city_3', 2020, 2)
]

population = [
    101,
    1010,
    201,
    2010,
    102,
    1020,
    202,
    2020,
    103,
    1030,
    203,
    2030
]

pop = pd.Series(population, index=index)
i = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(i)

print(pop.unstack())
print(pop.unstack(level=0))
print(pop.unstack(level=1))
print(pop.unstack(level=2))

               1     2
city_1 2010  101  1010
       2020  201  2010
city_2 2010  102  1020
       2020  202  2020
city_3 2010  103  1030
       2020  203  2030
        city_1  city_2  city_3
2010 1     101     102     103
     2    1010    1020    1030
2020 1     201     202     203
     2    2010    2020    2030
          2010  2020
city_1 1   101   201
       2  1010  2010
city_2 1   102   202
       2  1020  2020
city_3 1   103   203
       2  1030  2030
               1     2
city_1 2010  101  1010
       2020  201  2010
city_2 2010  102  1020
       2020  202  2020
city_3 2010  103  1030
       2020  203  2030


## NumPy конкатенация

In [56]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

print(np.concatenate([x, y, z]))

[1 2 3 4 5 6 7 8 9]


In [59]:
x = [[1, 2, 3]]
y = [[4, 5, 6]]
z = [[7, 8, 9]]

print(np.concatenate([x, y, z]))
print(np.concatenate([x, y, z], axis=0))
print(np.concatenate([x, y, z], axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


## Pandas - concat

In [60]:
ser1 = pd.Series(['a', 'b', 'c'], index=[1, 2, 3])
ser2 = pd.Series(['d', 'e', 'f'], index=[4, 5, 6])

print(pd.concat([ser1, ser2]))

1    a
2    b
3    c
4    d
5    e
6    f
dtype: object


In [64]:
ser1 = pd.Series(['a', 'b', 'c'], index=[1, 2, 3])
ser2 = pd.Series(['d', 'e', 'f'], index=[1, 2, 6])

print(pd.concat([ser1, ser2], verify_integrity=False))
print(pd.concat([ser1, ser2], ignore_index=True))
print(pd.concat([ser1, ser2], keys=['x', 'y']))

1    a
2    b
3    c
1    d
2    e
6    f
dtype: object
0    a
1    b
2    c
3    d
4    e
5    f
dtype: object
x  1    a
   2    b
   3    c
y  1    d
   2    e
   6    f
dtype: object


In [66]:
ser1 = pd.Series(['a', 'b', 'c'], index=[1, 2, 3])
ser2 = pd.Series(['b', 'c', 'f'], index=[4, 5, 6])

print(pd.concat([ser1, ser2], join="outer"))
print(pd.concat([ser1, ser2], join="inner"))

1    a
2    b
3    c
4    b
5    c
6    f
dtype: object
1    a
2    b
3    c
4    b
5    c
6    f
dtype: object
